surl/urls.py
from django.contrib import admin
from django.urls import path , re_path
from user.views import  login_page , register_page , home_page , contact_page , TrackMg ,LogOut
#from django.contrib.auth.views import logout
from shortener.views import HomeView, URLRedirectView
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracurl',TrackMg),
    path('logout',LogOut ),#,{'next_page':settings.LOGOUT_REDIRECT_URL},name  = 'logout' ),
    path('login',login_page ),
    path('join',register_page ),
    path('contact',contact_page),
    path('', HomeView.as_view()),
    re_path('(?P<shortcode>[\w-]+)/$', URLRedirectView.as_view(), name='scode'),
]

analytics/models.py
from django.db import models

# Create your models here.
from shortener.models import SURL


class ClickEventManager(models.Manager):
    def create_event(self, Instance):
        if isinstance(Instance, SURL):
            obj, created = self.get_or_create(s_url=Instance)
            obj.count += 1
            obj.save()
            return obj.count
        return None

class ClickEvent(models.Model):
    s_url    = models.ForeignKey(SURL, on_delete=models.CASCADE)
    count       = models.IntegerField(default=0)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = ClickEventManager()

    def __str__(self):
        return "{i}".format(i=self.count)

templates/Explorer/Explorer.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
 body {

      /* background-image: url(https://mdbootstrap.com/img/Photos/Horizontal/Nature/full%20page/img%2811%29.jpg) ; */

}
</style>
<body>

  <nav class="navbar navbar-expand-sm navbar-dark bg-primary ">

  <div class ="container">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/">Surl</a>
      </li>
     <li class="nav-item">
       <a class="nav-link" href="/tracurl">Features</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">Business</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="/tracurl">Explorer</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">Marketplace</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">Pricing</a>
     </li>
     {% if user.is_authenticated  %}
      <li class="nav-item">
        <a class="nav-link" href="#">Welcome <strong>{{ user.username }} <strong></a>
      </li>
     {% else %}
     <li class="nav-item ">
       <a class="nav-link" href="/login">Sign in </a>
     </li>

       <li class="nav-item " >
         <span class="nav-link">or </span>
       </li>
       <li class="nav-item ">
         <a class="nav-link" href="/join">Sign up </a>
       </li>
       {% endif %}

    </ul>
</div>
</nav>

<div class="container ">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Date</th>
      <th>Url</th>
      <th>Short Url</th>
      <th>Click all time</th>
    </tr>
  </thead>
  <tbody>
    {%  for i in object %}
        <tr>
          <td>{{  i.timestamp}}</td>
          <td>{{  i.url }}</td>
          <td><a href="surl.in/{{    i.shortcode }}">surl.in/{{i.shortcode }}</a></td>
          <td > {{  i.clickevent_set.count  }}&nbsp;&nbsp;<p class="fa fa-line-chart"></p></td>
        </tr>
    {%  endfor  %}
  </tbody>


  </table>
</div>